#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AESD Socket Server
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
NAME=aesdsocket
PIDFILE=/var/run/$NAME.pid

case "$1" in
  start)
    echo "Starting $NAME"
    start-stop-daemon -S -n $NAME -p $PIDFILE -m -b --startas $DAEMON -- -d
    ;;
  stop)
    echo "Stopping $NAME"
    start-stop-daemon -K -n $NAME -p $PIDFILE -s TERM
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

